import { CRISIS_LINES, CRISIS_TEL, EMERGENCY_TEL } from "@/lib/vent/intent";
import type { Metadata } from "next";
import { LegalPage } from "@/components/legal-page";

export const metadata: Metadata = {
  title: "Terms",
  description: "What Mind Weave VENT is, and what it is not.",
};

export default function TermsPage() {
  return (
    <LegalPage title="Terms">
      <h2>This is not therapy</h2>
      <p>
        Mind Weave is not a licensed therapist, doctor, or crisis service. VENT
        is for emotional support only. It does not diagnose, it does not treat,
        and it does not give medical advice. Nothing here replaces care from a
        qualified professional.
      </p>

      <h2>If you are in danger</h2>
      <p>
        Contact a human right now. Nigeria:{" "}
        <a href={`tel:${CRISIS_TEL}`}>{CRISIS_LINES.nigeria}</a>. Emergency:{" "}
        <a href={`tel:${EMERGENCY_TEL}`}>{CRISIS_LINES.emergency}</a>. If you are outside Nigeria, call your local
        emergency number.
      </p>

      <h2>It is an AI</h2>
      <p>
        Replies are generated by a language model. It can be wrong, and it can
        miss things a person would catch. Use your own judgement, and don&apos;t
        act on anything here that you would want a professional to confirm.
      </p>

      <h2>Fair use</h2>
      <p>
        Requests are rate limited so the service stays available to everyone.
        Don&apos;t use VENT to harass anyone, and don&apos;t try to break it.
      </p>

      <h2>No warranty</h2>
      <p>
        The service is provided as it is, without guarantees of availability or
        fitness for any particular purpose.
      </p>
    </LegalPage>
  );
}
